services:
    creatinote-db:
        environment:
            MARIADB_ROOT_PASSWORD: ${CREATINOTEDB_ROOT_PASSWORD}
            MARIADB_DATABASE: creatinote
            MARIADB_USER: creatinote
            MARIADB_PASSWORD: ${CREATINOTEDB_PASSWORD}
            #mariadb runs at port 3306 by default
        image: mariadb
        secrets:
        - db_root_password
        - db_password
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
    creatinote:
        depends_on:
            creatinote-db:
                condition: service_healthy
        image: creatinote:staging
        environment:
            DB_IP: creatinote-db
            DB_PORT: 3306
        ports:
            - 8080:8080
        secrets:
        - db_root_password
        - db_password

secrets:
  db_root_password:
    file: ./prod/db_root_password.txt
  db_password:
    file: ./prod/db_password.txt
